#!/usr/bin/env python3
"""Emit LaTeX macros for the ZM-1 open re-encoding sweep from reencode_bootstrap.csv.

Usage:
    python make_reencode_variables.py             # revision_results/reencode/reencode_bootstrap.csv
                                                  #   -> revision_results/reencode/reencode_variables.tex
    python make_reencode_variables.py SRC.csv DST.tex
"""
import argparse
import csv
import datetime
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
REENCODE_DIR = REPO_DIR / "revision_results" / "reencode"
NAMES = {
    "factory": "Factory", "tikhonov": "Tikhonov", "tikhonov_ordlim": "TikhonovOrdlim",
    "softlimit_20": "SoftTwenty", "softlimit_30": "SoftThirty", "softlimit_40": "SoftForty",
    "mmse_20": "Mmse", "Spcmic3OA_corpus": "SpcmicRef",
}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("src", nargs="?", type=Path, default=REENCODE_DIR / "reencode_bootstrap.csv",
                    help="reencode_bootstrap.csv from reencode_bootstrap.py (default %(default)s)")
    ap.add_argument("dst", nargs="?", type=Path, default=REENCODE_DIR / "reencode_variables.tex",
                    help="output .tex (default %(default)s)")
    args = ap.parse_args()

    with open(args.src, newline="") as f:
        rows = [r for r in csv.DictReader(f) if r["kind"] == "single" and r["config"] in NAMES]
    lines = ["% Auto-generated by make_reencode_variables.py - do not edit by hand.",
             f"% Generated: {datetime.datetime.now().isoformat(timespec='seconds')}",
             "% Single-array moving-block bootstrap (30-s blocks, 2000 replicates, seed 2026) on 1-s frame caches",
             "% \\ReencSpan<piece> is the range of the point estimates across the ZM-1 encoders", ""]
    pts = {}  # point estimates per piece; \ReencSpan<piece> is their range across the ZM-1 encoders
    for r in rows:
        key = f"{NAMES[r['config']]}{r['piece']}"
        pt, lo, hi, se = (float(r[k]) for k in ("rolloff_0_3_dB", "ci_lo", "ci_hi", "bootstrap_se"))
        lines += [f"\\newcommand{{\\Reenc{key}Pt}}{{{pt:.1f}}}",
                  f"\\newcommand{{\\Reenc{key}CILo}}{{{lo:.1f}}}",
                  f"\\newcommand{{\\Reenc{key}CIHi}}{{{hi:.1f}}}",
                  f"\\newcommand{{\\Reenc{key}SE}}{{{se:.2f}}}"]
        if r["config"] not in ("Spcmic3OA_corpus",):
            pts.setdefault(r["piece"], []).append(pt)
    for piece in pts:
        span = max(pts[piece]) - min(pts[piece])
        lines.append(f"\\newcommand{{\\ReencSpan{piece}}}{{{span:.0f}}}")
    args.dst.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.dst}: {len(rows)} rows; spans:",
          {p: round(max(pts[p]) - min(pts[p]), 1) for p in pts})


if __name__ == "__main__":
    main()
